"""Synthetic demo dataset -- run through the real pipeline, not faked.

Every document below is fed through extraction.extract_file() + infer_facts()
exactly as a real upload would be. The documents are generated text, not live
supplier data. This script is idempotent only for fresh DBs; delete data/cbam.db
for a clean demo if you re-run it.
"""
import os
import random
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app import db as dbm, engine, extraction, supplier_ops, util
random.seed(42)
SUPPLIERS = [
 ('Karadeniz Steel A.S.','Turkiye',[('Karadeniz Iskenderun Works','Basic oxygen furnace (BOF)')]),
 ('Ferrum Exports Pvt Ltd','India',[('Ferrum Rourkela Plant','Electric arc furnace (EAF)')]),
 ('Nile Aluminium Co','Egypt',[('Nile Aluminium Smelter Nag Hammadi','Primary electrolysis (Hall-Heroult)')]),
 ('Dnipro Metallurgical Combine','Ukraine',[('Dnipro No.3 Blast Furnace Complex','Blast furnace - basic oxygen furnace (BF-BOF)'),('Dnipro Rolling Mill','Hot rolling (downstream, secondary route)')]),
 ('Cerrado Aco Ltda','Brazil',[('Cerrado EAF Plant Goias','Electric arc furnace (EAF)')]),
 ('Highveld Alloys (Pty) Ltd','South Africa',[('Highveld Alloys Smelter','Primary electrolysis (Hall-Heroult)')]),
 ('Mekong Steel JSC','Vietnam',[('Mekong Steel Hai Phong','Basic oxygen furnace (BOF)')]),
]
PRODUCTS = [('72081000','iron_steel','Flat-rolled iron/steel, hot-rolled coils'),('72091600','iron_steel','Flat-rolled iron/steel, cold-rolled'),('72131000','iron_steel','Bars and rods, hot-rolled'),('73041900','iron_steel','Seamless tubes, iron or steel'),('76011000','aluminium','Unwrought aluminium, not alloyed'),('76041000','aluminium','Aluminium bars, rods and profiles')]

def txt(name,content): return name,content.encode('utf-8')
def ingest(c,tid,cid,uid,filename,data,doc_type,import_line_id=None,supplier_id=None,installation_id=None):
    sha=util.sha256_bytes(data)
    dup=c.execute('SELECT id FROM documents WHERE case_id=? AND sha256=?',(cid,sha)).fetchone()
    if dup:return dup['id']
    stored=f'{sha}{os.path.splitext(filename.lower())[1]}'
    with open(os.path.join(dbm.UP,stored),'wb') as fh:fh.write(data)
    text,meta=extraction.extract_file(filename,data);t=util.now()
    c.execute('INSERT INTO documents(tenant_id,case_id,import_line_id,supplier_id,installation_id,filename,stored_name,mime,doc_type,size_bytes,sha256,uploaded,uploaded_by,extracted_text,meta_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
     (tid,cid,import_line_id,supplier_id,installation_id,filename,stored,'text/plain',doc_type,len(data),sha,t,uid,text,'{}'))
    did=c.execute('SELECT last_insert_rowid()').fetchone()[0]
    for field,val,unit,loc,excerpt,confidence in extraction.infer_facts(text,meta):
        numeric=util.q(util.num(val)) if field in ('eu_tonnes','direct_intensity','indirect_intensity') else ''
        c.execute('INSERT INTO facts(tenant_id,case_id,document_id,import_line_id,supplier_id,installation_id,field,value,numeric_value,unit,location,source_excerpt,confidence,status,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
         (tid,cid,did,import_line_id,supplier_id,installation_id,field,val,numeric,unit,loc,excerpt,confidence,'candidate',t,t))
    return did

def seed_demo():
    dbm.init();c=dbm.db();tenant=c.execute('SELECT id FROM tenants ORDER BY id LIMIT 1').fetchone();tid=tenant['id']
    admin=c.execute('SELECT id FROM users WHERE tenant_id=? AND role=? LIMIT 1',(tid,'admin')).fetchone();uid=admin['id']
    engine.create_reporting_period(c,tid,'2026','2026-01-01','2026-12-31','2027-09-30');t=util.now()
    c.execute('INSERT INTO cases(tenant_id,company,case_name,period,sector,status,created,updated,notes) VALUES(?,?,?,?,?,?,?,?,?)',
      (tid,'Atlas Metals Import GmbH','2026 Annual CBAM Case','2026','iron_steel','working',t,t,'Synthetic demo case generated by app/demo.py.'))
    cid=c.execute('SELECT last_insert_rowid()').fetchone()[0];supplier_ids={};installations_by_supplier={}
    for name,country,insts in SUPPLIERS:
        sid=engine.create_supplier(c,tid,name,country,contact_email=name.lower().split()[0]+'@example-supplier.com');supplier_ids[name]=sid;installations_by_supplier[name]=[]
        for iname,route in insts:installations_by_supplier[name].append(engine.create_installation(c,tid,sid,iname,country,production_route=route))
    product_ids={cn:engine.create_product(c,tid,cn,desc,sector) for cn,sector,desc in PRODUCTS}
    default_map={'iron_steel':(1.98,.14),'aluminium':(1.54,5.20)};all_installations=[(sn,iid) for sn,ids in installations_by_supplier.items() for iid in ids]
    inv_counter,ship_counter,n_lines=1000,5000,0;blocked_target,conflict_target=8,7
    for imp_idx in range(14):
        supplier_name=SUPPLIERS[imp_idx%len(SUPPLIERS)][0];sid=supplier_ids[supplier_name];installation_id=random.choice(installations_by_supplier[supplier_name])
        installation_row=c.execute('SELECT * FROM installations WHERE id=?',(installation_id,)).fetchone()
        import_id=engine.create_import(c,tid,cid,reference=f'ATL-2026-{1000+imp_idx}',mode=random.choice(['sea','road','rail']),arrival_date=f'2026-{(imp_idx%9)+1:02d}-{(imp_idx*3%27)+1:02d}')
        for _ in range(random.randint(2,4)):
            cn,sector,desc=random.choice(PRODUCTS);qty=round(random.uniform(18,60),3);invoice_ref=f'INV-2026-{inv_counter}';inv_counter+=1;shipment_ref=f'SHP-2026-{ship_counter}';ship_counter+=1;country=dict((n,c2) for n,c2,_ in SUPPLIERS)[supplier_name]
            line_id=engine.create_import_line(c,tid,cid,import_id=import_id,product_id=product_ids[cn],cn_code=cn,supplier_id=sid,installation_id=installation_id,invoice_ref=invoice_ref,origin_country=country,quantity=str(qty),quantity_unit='t',customs_ref=f'MRN2026{1000000+n_lines}');n_lines+=1
            mismatch=n_lines<=conflict_target and random.random()<.6;packing_qty=qty if not mismatch else round(qty+random.choice([-1.2,1.5,2.3]),3)
            invoice_txt=(f'COMMERCIAL INVOICE\nInvoice Number: {invoice_ref}\nSupplier: {supplier_name}\nInstallation: {installation_row["name"]}\nCountry of origin: {country}\nShipment Ref: {shipment_ref}\nCN code: {cn}\nDescription: {desc}\nNet weight: {qty} t\n')
            ingest(c,tid,cid,uid,f'{invoice_ref}_invoice.txt',invoice_txt.encode(),'commercial_invoice',line_id,sid,installation_id)
            packing_txt=(f'PACKING LIST\nShipment Ref: {shipment_ref}\nInvoice Number: {invoice_ref}\nSupplier: {supplier_name}\nNet weight: {packing_qty} t\nPackages: {random.randint(4,40)}\n')
            ingest(c,tid,cid,uid,f'{invoice_ref}_packing_list.txt',packing_txt.encode(),'packing_list',line_id,sid,installation_id)
            if n_lines>blocked_target:
                for name,cat in [('Commercial invoice','commercial'),('Packing list','shipping')]:
                    c.execute('INSERT INTO evidence(tenant_id,case_id,name,category,status,scope_type,scope_id,source,updated) VALUES(?,?,?,?,?,?,?,?,?)',(tid,cid,name,cat,'complete','import_line',line_id,'demo_seed',util.now()))
                c.execute("UPDATE import_lines SET status='reconciled' WHERE id=?",(line_id,))
            else:c.execute("UPDATE import_lines SET status='blocked' WHERE id=?",(line_id,))
    method_actual=engine.lookup_methodology(c,'ACTUAL_VERIFIED')
    for idx,(sname,iid) in enumerate(all_installations):
        inst=c.execute('SELECT * FROM installations WHERE id=?',(iid,)).fetchone();product=c.execute('SELECT sector FROM products p JOIN import_lines l ON l.product_id=p.id WHERE l.installation_id=? LIMIT 1',(iid,)).fetchone();sector=product['sector'] if product else 'iron_steel';base_direct,base_indirect=default_map.get(sector,(1.5,1.0));actual_direct=round(base_direct*random.uniform(.7,.95),4);actual_indirect=round(base_indirect*random.uniform(.6,1.1),4);bucket=idx%5
        decl_txt=(f'SUPPLIER DECLARATION OF EMBEDDED EMISSIONS\nSupplier: {sname}\nInstallation: {inst["name"]}\nCountry of origin: {inst["country"]}\nDirect emissions intensity: {actual_direct}\nIndirect emissions intensity: {actual_indirect}\n')
        if bucket==4:continue
        did=ingest(c,tid,cid,uid,f'{inst["name"].replace(" ","_")}_declaration.txt',decl_txt.encode(),'supplier_declaration',supplier_id=supplier_ids[sname],installation_id=iid)
        if bucket==3:
            conflict_txt=decl_txt.replace(f'Direct emissions intensity: {actual_direct}',f'Direct emissions intensity: {round(actual_direct*1.6,4)}')
            ingest(c,tid,cid,uid,f'{inst["name"].replace(" ","_")}_declaration_v2.txt',conflict_txt.encode(),'supplier_declaration',supplier_id=supplier_ids[sname],installation_id=iid);continue
        for f in c.execute("SELECT * FROM facts WHERE tenant_id=? AND document_id=? AND status='candidate'",(tid,did)).fetchall():c.execute("UPDATE facts SET status='verified',verified_by=?,verified_at=?,updated=? WHERE id=?",(uid,util.now(),util.now(),f['id']))
        c.execute('INSERT INTO emissions_data(tenant_id,installation_id,methodology_id,direct_intensity,indirect_intensity,status,created,updated) VALUES(?,?,?,?,?,?,?,?)',(tid,iid,method_actual['id'] if method_actual else None,str(actual_direct),str(actual_indirect),'validated',util.now(),util.now()))
        for name,cat,scope_type,scope_id in [('Embedded emissions data','emissions','installation',iid),('Producer / installation identity','installation','installation',iid),('Production quantity / activity data','activity','installation',iid),('Supplier declaration / upstream evidence','supplier','supplier',supplier_ids[sname])]:
            c.execute('INSERT INTO evidence(tenant_id,case_id,name,category,status,scope_type,scope_id,source,updated) VALUES(?,?,?,?,?,?,?,?,?)',(tid,cid,name,cat,'complete',scope_type,scope_id,'supplier_response',util.now()))
    c.commit();engine.sync_requirements(c,tid,cid);engine.run_reconciliation(c,tid,cid,uid);c.commit()
    n=supplier_ops.generate_all_supplier_requests(c,tid,cid,uid,deadline='2026-10-15');reqs=c.execute('SELECT * FROM supplier_requests WHERE tenant_id=? AND case_id=?',(tid,cid)).fetchall()
    for i,r in enumerate(reqs):
        bucket=i%4
        if bucket==0:
            supplier_ops.send_request(c,tid,r['id'],uid);c.execute("UPDATE supplier_requests SET status='OVERDUE',deadline='2026-08-01',escalation_level=2,updated=? WHERE id=?",(util.now(),r['id']))
        elif bucket==1:supplier_ops.send_request(c,tid,r['id'],uid)
        elif bucket==2:supplier_ops.send_request(c,tid,r['id'],uid);supplier_ops.mark_responded(c,tid,r['id'],uid,validated=True)
    c.commit()
    reconciled_lines=c.execute("SELECT id FROM import_lines WHERE tenant_id=? AND case_id=? AND status='reconciled'",(tid,cid)).fetchall()
    for l in reconciled_lines[:25]:engine.compute_import_line_calculation(c,tid,uid,cid,l['id'],{})
    c.commit();engine.generate_declaration_package(c,tid,cid,uid);c.commit();sc,rd=engine.readiness(c,tid,cid)
    print(f'Demo tenant seeded. Case #{cid} readiness={sc}% lines={rd["import_lines_total"]} blocked={rd["import_lines_blocked"]} open_exceptions={rd["open_issues"]} suppliers={len(supplier_ids)} installations={len(all_installations)} supplier_requests={len(reqs)}')
    c.close();return cid
if __name__=='__main__':seed_demo()
