-- CBEOS PostgreSQL baseline schema. App tables are protected from direct Data API access.

CREATE TABLE IF NOT EXISTS tenants(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, created TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS users(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, email TEXT NOT NULL,
  password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'reviewer', active INTEGER NOT NULL DEFAULT 1,
  created TEXT NOT NULL, UNIQUE(tenant_id,email),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS sessions(
  id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, csrf TEXT NOT NULL, expires TEXT NOT NULL,
  created TEXT NOT NULL, ip TEXT DEFAULT '',
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

-- Operational workspace: a bounded unit of evidence + review for one importer/period.
CREATE TABLE IF NOT EXISTS cases(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, company TEXT NOT NULL, case_name TEXT NOT NULL,
  period TEXT NOT NULL, sector TEXT DEFAULT '', status TEXT DEFAULT 'working',
  created TEXT NOT NULL, updated TEXT NOT NULL, approved_at TEXT DEFAULT '', notes TEXT DEFAULT '',
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS reporting_periods(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, code TEXT NOT NULL, start_date TEXT DEFAULT '',
  end_date TEXT DEFAULT '', declaration_deadline TEXT DEFAULT '', status TEXT DEFAULT 'open',
  created TEXT NOT NULL, UNIQUE(tenant_id,code),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS suppliers(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, name TEXT NOT NULL, country TEXT DEFAULT '',
  contact_name TEXT DEFAULT '', contact_email TEXT DEFAULT '', external_ref TEXT DEFAULT '',
  status TEXT DEFAULT 'active', notes TEXT DEFAULT '', created TEXT NOT NULL, updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS installations(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, supplier_id INTEGER, name TEXT NOT NULL,
  country TEXT DEFAULT '', unlocode TEXT DEFAULT '', production_route TEXT DEFAULT '',
  monitoring_plan_status TEXT DEFAULT 'unknown', status TEXT DEFAULT 'active',
  created TEXT NOT NULL, updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS cn_reference(
  code TEXT PRIMARY KEY, description TEXT NOT NULL, sector TEXT NOT NULL, aggregated_category TEXT DEFAULT '');

CREATE TABLE IF NOT EXISTS products(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, cn_code TEXT NOT NULL, description TEXT DEFAULT '',
  sector TEXT DEFAULT '', created TEXT NOT NULL, updated TEXT NOT NULL, UNIQUE(tenant_id,cn_code),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);

-- One "import" = one customs consignment/declaration header; it groups import lines.
CREATE TABLE IF NOT EXISTS imports(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, reference TEXT DEFAULT '',
  mode TEXT DEFAULT 'sea', arrival_date TEXT DEFAULT '', customs_office TEXT DEFAULT '',
  status TEXT DEFAULT 'open', created TEXT NOT NULL, updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS import_lines(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, import_id INTEGER,
  product_id INTEGER, supplier_id INTEGER, installation_id INTEGER, reporting_period_id INTEGER,
  invoice_ref TEXT DEFAULT '', cn_code TEXT DEFAULT '', description TEXT DEFAULT '',
  origin_country TEXT DEFAULT '', quantity TEXT DEFAULT '', quantity_unit TEXT DEFAULT 't',
  customs_value TEXT DEFAULT '', customs_ref TEXT DEFAULT '', production_route TEXT DEFAULT '',
  applicability TEXT DEFAULT 'needs_review', status TEXT DEFAULT 'candidate',
  created TEXT NOT NULL, updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(import_id) REFERENCES imports(id) ON DELETE SET NULL,
  FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL,
  FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
  FOREIGN KEY(installation_id) REFERENCES installations(id) ON DELETE SET NULL,
  FOREIGN KEY(reporting_period_id) REFERENCES reporting_periods(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS documents(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL,
  import_line_id INTEGER, supplier_id INTEGER, installation_id INTEGER,
  filename TEXT NOT NULL, stored_name TEXT NOT NULL, mime TEXT DEFAULT '', doc_type TEXT DEFAULT 'other',
  size_bytes INTEGER DEFAULT 0, sha256 TEXT NOT NULL, version INTEGER DEFAULT 1, superseded_by INTEGER,
  uploaded TEXT NOT NULL, uploaded_by INTEGER, extracted_text TEXT DEFAULT '', meta_json TEXT DEFAULT '{}',
  status TEXT DEFAULT 'processed', scan_status TEXT DEFAULT 'clean',
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(import_line_id) REFERENCES import_lines(id) ON DELETE SET NULL,
  FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
  FOREIGN KEY(installation_id) REFERENCES installations(id) ON DELETE SET NULL,
  UNIQUE(case_id,sha256));

CREATE TABLE IF NOT EXISTS facts(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, document_id INTEGER NOT NULL,
  import_line_id INTEGER, supplier_id INTEGER, installation_id INTEGER,
  field TEXT NOT NULL, value TEXT NOT NULL, numeric_value TEXT DEFAULT '', unit TEXT DEFAULT '',
  normalized_value TEXT DEFAULT '', unit_normalized TEXT DEFAULT '', conversion_note TEXT DEFAULT '',
  location TEXT DEFAULT '', source_excerpt TEXT DEFAULT '', confidence TEXT DEFAULT 'medium',
  status TEXT DEFAULT 'candidate', verified_by INTEGER, verified_at TEXT DEFAULT '',
  created TEXT NOT NULL, updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE,
  FOREIGN KEY(import_line_id) REFERENCES import_lines(id) ON DELETE SET NULL,
  FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
  FOREIGN KEY(installation_id) REFERENCES installations(id) ON DELETE SET NULL,
  FOREIGN KEY(verified_by) REFERENCES users(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS evidence(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, name TEXT NOT NULL,
  category TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'missing', document_id INTEGER,
  scope_type TEXT DEFAULT 'case', scope_id INTEGER,
  owner TEXT DEFAULT '', source TEXT DEFAULT '', note TEXT DEFAULT '', expires_at TEXT DEFAULT '',
  updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS evidence_links(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, evidence_id INTEGER NOT NULL, fact_id INTEGER, entity_type TEXT DEFAULT '',
  entity_id INTEGER, note TEXT DEFAULT '',
  FOREIGN KEY(evidence_id) REFERENCES evidence(id) ON DELETE CASCADE,
  FOREIGN KEY(fact_id) REFERENCES facts(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS evidence_requirements(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, name TEXT NOT NULL,
  category TEXT NOT NULL, applicability TEXT DEFAULT 'operational', status TEXT DEFAULT 'missing',
  scope_type TEXT DEFAULT 'case', scope_id INTEGER DEFAULT 0, reason TEXT DEFAULT '',
  created TEXT NOT NULL, updated TEXT NOT NULL, UNIQUE(case_id,name,scope_type,scope_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);

-- Exception queue: the operational product. Status machine documented in engine.py.
CREATE TABLE IF NOT EXISTS exceptions(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, title TEXT NOT NULL,
  category TEXT DEFAULT 'general', severity TEXT NOT NULL, status TEXT DEFAULT 'OPEN',
  affected_entity_type TEXT DEFAULT '', affected_entity_id INTEGER,
  detail TEXT DEFAULT '', field TEXT DEFAULT '', supporting_evidence TEXT DEFAULT '',
  conflicting_evidence TEXT DEFAULT '', recommended_action TEXT DEFAULT '',
  financial_impact_eur TEXT DEFAULT '',
  owner TEXT DEFAULT '', deadline TEXT DEFAULT '', resolution TEXT DEFAULT '',
  reviewer_id INTEGER, source TEXT DEFAULT '', created TEXT NOT NULL, updated TEXT NOT NULL,
  closed_by INTEGER,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(reviewer_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY(closed_by) REFERENCES users(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS supplier_requests(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, supplier_id INTEGER NOT NULL,
  requirement_name TEXT DEFAULT '', title TEXT NOT NULL, draft TEXT DEFAULT '',
  status TEXT DEFAULT 'DRAFT', deadline TEXT DEFAULT '', sent_at TEXT DEFAULT '',
  responded_at TEXT DEFAULT '', escalation_level INTEGER DEFAULT 0,
  created_by INTEGER, created TEXT NOT NULL, updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS methodologies(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, kind TEXT NOT NULL,
  description TEXT DEFAULT '', source_id INTEGER);

CREATE TABLE IF NOT EXISTS emissions_data(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, installation_id INTEGER NOT NULL,
  reporting_period_id INTEGER, methodology_id INTEGER,
  direct_intensity TEXT DEFAULT '', indirect_intensity TEXT DEFAULT '', unit TEXT DEFAULT 'tCO2e/t',
  source_fact_id INTEGER, status TEXT DEFAULT 'candidate', created TEXT NOT NULL, updated TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(installation_id) REFERENCES installations(id) ON DELETE CASCADE,
  FOREIGN KEY(methodology_id) REFERENCES methodologies(id) ON DELETE SET NULL,
  FOREIGN KEY(source_fact_id) REFERENCES facts(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS regulatory_sources(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT UNIQUE NOT NULL, title TEXT NOT NULL, effective_date TEXT DEFAULT '',
  url TEXT DEFAULT '', status TEXT DEFAULT 'active', notes TEXT DEFAULT '', created TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS rule_sets(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT UNIQUE NOT NULL, version TEXT NOT NULL, effective_from TEXT NOT NULL,
  source_id INTEGER, description TEXT NOT NULL, status TEXT DEFAULT 'active', created TEXT NOT NULL,
  FOREIGN KEY(source_id) REFERENCES regulatory_sources(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS default_values(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_set_id INTEGER NOT NULL, sector TEXT NOT NULL, cn_prefix TEXT DEFAULT '',
  production_route TEXT DEFAULT '', country TEXT DEFAULT '',
  direct_default TEXT NOT NULL, indirect_default TEXT DEFAULT '0', total_default TEXT DEFAULT '', unit TEXT DEFAULT 'tCO2e/t',
  confidence TEXT DEFAULT 'illustrative', markup_note TEXT DEFAULT '', source_id INTEGER,
  FOREIGN KEY(rule_set_id) REFERENCES rule_sets(id) ON DELETE CASCADE,
  FOREIGN KEY(source_id) REFERENCES regulatory_sources(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS default_value_markups(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_set_id INTEGER NOT NULL, sector TEXT NOT NULL, year INTEGER NOT NULL,
  markup_pct TEXT NOT NULL, source_id INTEGER, UNIQUE(rule_set_id,sector,year),
  FOREIGN KEY(rule_set_id) REFERENCES rule_sets(id) ON DELETE CASCADE,
  FOREIGN KEY(source_id) REFERENCES regulatory_sources(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS free_allocation_schedule(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_set_id INTEGER NOT NULL, year INTEGER NOT NULL,
  cbam_factor_pct TEXT NOT NULL, free_allocation_remaining_pct TEXT NOT NULL, source_id INTEGER,
  UNIQUE(rule_set_id,year),
  FOREIGN KEY(rule_set_id) REFERENCES rule_sets(id) ON DELETE CASCADE,
  FOREIGN KEY(source_id) REFERENCES regulatory_sources(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS cbam_benchmarks(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_set_id INTEGER NOT NULL, sector TEXT NOT NULL, production_route TEXT NOT NULL,
  benchmark_tco2e_per_t TEXT NOT NULL, confidence TEXT DEFAULT 'illustrative', source_id INTEGER,
  UNIQUE(rule_set_id,production_route),
  FOREIGN KEY(rule_set_id) REFERENCES rule_sets(id) ON DELETE CASCADE,
  FOREIGN KEY(source_id) REFERENCES regulatory_sources(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS certificate_prices(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_set_id INTEGER, period TEXT NOT NULL, price_eur TEXT NOT NULL,
  source_id INTEGER, observed_at TEXT NOT NULL,
  FOREIGN KEY(rule_set_id) REFERENCES rule_sets(id) ON DELETE SET NULL,
  FOREIGN KEY(source_id) REFERENCES regulatory_sources(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS calculation_runs(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, import_line_id INTEGER,
  rule_set_id INTEGER NOT NULL, methodology_id INTEGER, run_type TEXT NOT NULL,
  created TEXT NOT NULL, created_by INTEGER, input_snapshot TEXT NOT NULL, result_json TEXT NOT NULL,
  status TEXT DEFAULT 'scenario', review_status TEXT DEFAULT 'unreviewed',
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(import_line_id) REFERENCES import_lines(id) ON DELETE SET NULL,
  FOREIGN KEY(rule_set_id) REFERENCES rule_sets(id) ON DELETE RESTRICT);

CREATE TABLE IF NOT EXISTS verification_records(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, installation_id INTEGER NOT NULL,
  reporting_period_id INTEGER, readiness_score INTEGER DEFAULT 0, checklist_json TEXT DEFAULT '[]',
  status TEXT DEFAULT 'NOT_READY', computed_at TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(installation_id) REFERENCES installations(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS declaration_packages(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL,
  generated_at TEXT NOT NULL, generated_by INTEGER, manifest_json TEXT NOT NULL, sha256 TEXT NOT NULL,
  status TEXT DEFAULT 'draft',
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS regulatory_updates(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT UNIQUE NOT NULL, title TEXT NOT NULL, announced_date TEXT NOT NULL,
  effective_date TEXT DEFAULT '', source_id INTEGER, affected_scope TEXT DEFAULT '', impact TEXT DEFAULT '',
  product_implication TEXT DEFAULT '', status TEXT DEFAULT 'WATCH', created TEXT NOT NULL,
  FOREIGN KEY(source_id) REFERENCES regulatory_sources(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS approvals(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL, decision TEXT NOT NULL,
  comment TEXT DEFAULT '', created TEXT NOT NULL, actor_id INTEGER,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL);

-- Append-only, hash-chained per tenant. Never UPDATE/DELETE rows here.
CREATE TABLE IF NOT EXISTS audit(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER, case_id INTEGER, actor_id INTEGER, action TEXT NOT NULL,
  detail TEXT DEFAULT '', created TEXT NOT NULL, prev_hash TEXT DEFAULT '', hash TEXT NOT NULL,
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE SET NULL,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE SET NULL,
  FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL);

-- Durable, inspectable multi-agent workflow runs and agent-to-agent messages.
CREATE TABLE IF NOT EXISTS agent_runs(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, case_id INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'RUNNING', provider TEXT DEFAULT 'rules-only',
  started_at TEXT NOT NULL, finished_at TEXT DEFAULT '', summary_json TEXT DEFAULT '{}', error_code TEXT DEFAULT '',
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_agent_runs_case ON agent_runs(tenant_id,case_id,id);
CREATE TABLE IF NOT EXISTS agent_messages(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id INTEGER NOT NULL, sequence_no INTEGER NOT NULL,
  from_agent TEXT NOT NULL, to_agent TEXT NOT NULL, message_type TEXT NOT NULL DEFAULT 'handoff',
  body TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL,
  prev_hash TEXT DEFAULT '', message_hash TEXT NOT NULL DEFAULT '',
  UNIQUE(run_id,sequence_no),
  FOREIGN KEY(run_id) REFERENCES agent_runs(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_agent_messages_run ON agent_messages(run_id,sequence_no);

CREATE INDEX IF NOT EXISTS idx_cases_tenant ON cases(tenant_id);
CREATE INDEX IF NOT EXISTS idx_docs_case ON documents(case_id);
CREATE INDEX IF NOT EXISTS idx_facts_case ON facts(case_id);
CREATE INDEX IF NOT EXISTS idx_facts_line ON facts(import_line_id);
CREATE INDEX IF NOT EXISTS idx_lines_case ON import_lines(case_id);
CREATE INDEX IF NOT EXISTS idx_lines_supplier ON import_lines(supplier_id);
CREATE INDEX IF NOT EXISTS idx_lines_installation ON import_lines(installation_id);
CREATE INDEX IF NOT EXISTS idx_exceptions_case ON exceptions(case_id);
CREATE INDEX IF NOT EXISTS idx_exceptions_status ON exceptions(tenant_id,status);
CREATE INDEX IF NOT EXISTS idx_audit_tenant ON audit(tenant_id,id);
CREATE INDEX IF NOT EXISTS idx_reqs_case ON evidence_requirements(case_id);

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reporting_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cn_reference ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.methodologies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emissions_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.regulatory_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rule_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.default_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.default_value_markups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.free_allocation_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbam_benchmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificate_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calculation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.declaration_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.regulatory_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;

-- The target project contains an automatic RLS helper; it must not be callable through PostgREST.
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated;
